# Generated by Django 4.2 on 2025-10-07 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('caption_en', models.TextField(blank=True)),
                ('caption_es', models.TextField(blank=True, null=True)),
                ('caption_fr', models.TextField(blank=True, null=True)),
                ('caption_de', models.TextField(blank=True, null=True)),
                ('caption_hi', models.TextField(blank=True, null=True)),
                ('caption_zh', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.IntegerField(default=0)),
                ('image_width', models.IntegerField(default=0)),
                ('image_height', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Captioned Image',
                'verbose_name_plural': 'Captioned Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
